"use client";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ptBR from "antd/locale/pt_BR";
import { ConfigProvider } from "antd";
import { StyleProvider } from "@ant-design/cssinjs";
import "../../public/antd.min.css"; // add this line
import "./globals.css";
import { theme } from "./theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConfigProvider locale={ptBR} theme={theme}>
          <StyleProvider hashPriority="high">{children}</StyleProvider>
        </ConfigProvider>
      </body>
    </html>
  );
}
