"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ptBR from "antd/locale/pt_BR";
import { ConfigProvider } from "antd";
import { StyleProvider } from "@ant-design/cssinjs";
import "../../public/antd.min.css";
import "./globals.css";
import { theme } from "../theme";
import { AuthProvider } from "@/contexts/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body id="app" className={inter.className}>
        <ConfigProvider locale={ptBR} theme={theme}>
          <StyleProvider hashPriority="high">
            <AuthProvider>{children}</AuthProvider>
          </StyleProvider>
        </ConfigProvider>
      </body>
    </html>
  );
}
